security:
    # Configuration des hacheurs de mots de passe pour l'entité User
    password_hashers:
        App\Entity\User:
            algorithm: auto
    # Activation du gestionnaire d'authentification
    enable_authenticator_manager: true

    # Définition du fournisseur d'utilisateurs en mémoire
    providers:
        users_in_memory: { memory: null }

    # Configuration des pare-feux
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            # Autres configurations de pare-feu

    # Contrôle d'accès
    access_control:
        # Configurez ici les contrôles d'accès

# Configuration spécifique aux tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur minimale pour bcrypt
                time_cost: 3 # Valeur minimale pour argon
                memory_cost: 10 # Valeur minimale pour argon